# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mensagens.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmensagens.proto\x12\x08mensagem\"\x8f\x01\n\x07Request\x12\x0c\n\x04tipo\x18\x02 \x01(\x05\x12\x0c\n\x04nome\x18\x03 \x01(\t\x12\x13\n\x06ligado\x18\x04 \x01(\x08H\x00\x88\x01\x01\x12\x18\n\x0btemperatura\x18\x05 \x01(\x02H\x01\x88\x01\x01\x12\x13\n\x06volume\x18\x06 \x01(\x05H\x02\x88\x01\x01\x42\t\n\x07_ligadoB\x0e\n\x0c_temperaturaB\t\n\x07_volume\"/\n\x08Response\x12#\n\x08requests\x18\x01 \x03(\x0b\x32\x11.mensagem.Requestb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mensagens_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=30
  _REQUEST._serialized_end=173
  _RESPONSE._serialized_start=175
  _RESPONSE._serialized_end=222
# @@protoc_insertion_point(module_scope)
