# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotobuf.proto\x12\x08protobuf\"\x14\n\x06Status\x12\n\n\x02on\x18\x01 \x01(\x08\"\x07\n\x05Vazio\"C\n\x07Request\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\x05\x12\n\n\x02on\x18\x02 \x01(\x08\x12\x12\n\x05value\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_value\"/\n\x08Response\x12#\n\x08requests\x18\x01 \x03(\x0b\x32\x11.protobuf.Request2e\n\x04Turn\x12-\n\x06TurnOn\x12\x0f.protobuf.Vazio\x1a\x10.protobuf.Status\"\x00\x12.\n\x07TurnOff\x12\x0f.protobuf.Vazio\x1a\x10.protobuf.Status\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=28
  _STATUS._serialized_end=48
  _VAZIO._serialized_start=50
  _VAZIO._serialized_end=57
  _REQUEST._serialized_start=59
  _REQUEST._serialized_end=126
  _RESPONSE._serialized_start=128
  _RESPONSE._serialized_end=175
  _TURN._serialized_start=177
  _TURN._serialized_end=278
# @@protoc_insertion_point(module_scope)
